### ISSUE TITLE
Your pre-trained model cannot be downloaded

### ISSUE THREAD

**Issue by wjk158** [zcanfes/3d-lmnet-pytorch#2]
Hello, your pre-trained model cannot be downloaded because the Google Cloud Drive link is invalid. Can we share the pre trained model again? thanks

**Comment by lmc2000** [comment]
预训练模型你找到了吗

**Comment by wjk158** [comment]
没有，作者没有回复我

**Comment by lmc2000** [comment]
那你配置原始tf的版本成功了吗

**Comment by wjk158** [comment]
这个pytorch版本能用，我就没有配置tf版本

**Comment by lmc2000** [comment]
那你有shapenet的预训练模型吗，我就想test和评估一下模型

**Comment by zcanfes** [comment]
Hello @wjk158  and @lmc2000,

I apologize for the delay in responding to this issue. Thank you for your patience. Also thank you for your interest in our implementation.

It seems that the pre-trained models have been removed from the provided Google Cloud Drive link. I'm working on recovering these models and will notify you once the models are re-uploaded. If you have any further questions or require additional assistance, please feel free to ask.

**Comment by zcanfes** [comment]
Hello @lmc2000 and @wjk158, 

I've uploaded the pretrained models to Google Drive and provided the links for download in the README. If you have any issues downloading them, you can let me know. For now, I'm closing this issue.
